### ISSUE TITLE
create a slower cadence version stream for Jenkins X 3 ready for beta

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx3-versions#1737]
One of the most common themes of feedback for Jenkins X 1 ad 2 was the rate of constant change was hard to keep up with, new features were considered risky because they'd not been used aside from in tests and it was hard for users to know what to expect.

With jx3 we have the big advantage of using `kpt` to get release updates and right now users run in their own clusters git repo
```
jx gitops upgrade
```
To pull in updates from the jxr-versions (this repo) version stream.

This approach has been great during development of jx3 and the OSS community have been quick to provide feedback and help with the maturity of features.  As we start planning for a beta release of jx3 we should consider creating a slower cadence version stream that we release once per month, for example, so that users who require that extra confidence can consume.

For folks that prefer to keep on the latest and greatest version stream that's still totally fine, Jenkins X auto upgrades its own infrastructure from the latest version stream and will continue to do that.

Upon release of the latest version stream we could create / upgrade existing PR on the stable version stream and merge this once per month when we are happy.  

The other advantage here is we can include release notes that describe note worthy information and also help us inform users what is planned for the next release so they can plan.  We can include links to guides and feature docs on the website so it is clearer what is in the upgrade.

We could use the issue tracker on the latest version to triage issues that must be resolved before the stable release.

We could add a new jx command to switch the kpt files in users cluster git repo to use the latest or stable version stream and let `kpt` do the rest.

If the details work then we should enable this for the first jx beta release.

Questions
What do we call the version stream repos?  jx-versions? jx-vs (version stream as it contains more than versions)?
Do we want to call it LTS (long time support) or stable or something else? jx3-vs-stable?
How often should we try and release?
Should we rename this repo?  jx3-vs-latest, jx3-vs-brave something else?
What else to think about?

**Comment by tomhobson** [comment]
**imho:**

jx-versions because it will be the easiest to locate for newer users

Stable and beta are sometimes confusing sentiments. Initially I'm guessing you'll still be in beta but you'll also have a stable release (which is also in beta). I think LTS makes more sense in this regard.

Can't really comment as don't know your cadence.

I guess the branch system could work fine, if that's supported. The main/master branch is the most up to date. And an LTS branch for all us scaredy cats.

I guess just avoiding the issue of stale-ness of charts (especially LTS being forgotten about) in future is something to think about.

**Comment by jstrachan** [comment]
closing this as we've got the LTS now:
https://jenkins-x.io/v3/admin/setup/upgrades/lts/
