### ISSUE TITLE
AWS region on external secrets is not correctly set

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx3-versions#2757]
External secrets cannot find the secrets in secretsmanager even when all policies and permissions are correct.  Investigating the deployment in the secret-infra namespace, it shows

       spec:
        containers:
        - env:
          - name: AWS_DEFAULT_REGION
            value: us-west-2
          - name: AWS_REGION
            value: us-west-2

Editing the deployment by hand and setting the correct regions manually makes the external secrets able to fetch again, for a while. 
Strangely, the set up in the versionstream values seem to be correct, not sure what is happening here. 
      https://github.com/jenkins-x/jx3-versions/blob/master/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl#L18

**Comment by deckerp** [comment]
Someone pointed out to me that the region is conditional.

{{- if eq .Values.jxRequirements.secretStorage "secretsManager" }}
  AWS_REGION: {{ .Values.jxRequirements.cluster.region }}

Then we looked in our jx-requirements.xml and we had coded "secretsManager", but in our repo something else (JX3?) had changed that to "asm". Therefore it went with the default of "us-west-2".
